services:
  - type: web
    name: revision-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
